AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: SAM template for backend API (no auth)

Resources:
  BackendApi:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lambda.handler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 512
      Timeout: 30
      Events:
        AnyApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          NODE_ENV: "production"
          MONGODB_URI: "mongodb+srv://damian-admin:vn6NOD7Wvj6uMuQ1@production-cluster.u37gt.mongodb.net/user_management?retryWrites=true&w=majority&appName=production-cluster"
          DB_USERS: "user_management"
          FRONTEND_URL: "*"
