// constants/recommendationConstants.js
export const FETCH_RECOMMENDATIONS_REQUEST = "FETCH_RECOMMENDATIONS_REQUEST"
export const FETCH_RECOMMENDATIONS_SUCCESS = "FETCH_RECOMMENDATIONS_SUCCESS"
export const FETCH_RECOMMENDATIONS_FAIL = "FETCH_RECOMMENDATIONS_FAIL"
export const SET_SELECTED_SKILL = "SET_SELECTED_SKILL"
export const SET_SORT_OPTION = "SET_SORT_OPTION"
