// constants/userConstants.js
/**
 * User authentication action types
 */
export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST"
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS"
export const USER_REGISTER_FAIL = "USER_REGISTER_FAIL"
export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL"
export const USER_LOGOUT = "USER_LOGOUT"

export const CHECK_AUTH_REQUEST = "CHECK_AUTH_REQUEST"
export const CHECK_AUTH_SUCCESS = "CHECK_AUTH_SUCCESS"
export const CHECK_AUTH_FAIL = "CHECK_AUTH_FAIL"
